version: 2
jobs:
  # Runs JavaScript tests on Node 8
  test-js-node-8:
    docker:
      - image: circleci/node:8

    working_directory: ~/italia-app

    steps:
      - checkout

      # Restore dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      # Install node dependencies
      - run: npm install --no-package-lock --no-spin --no-progress

      # Save node cache
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
        
      # Run tests
      - run: npm test

  # Build js bundle
  build-js-bundle:
    docker:
      - image: circleci/node:8

    working_directory: ~/italia-app

    steps:
      - checkout

      # Restore dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      # Install node dependencies
      - run: npm install --no-package-lock --no-spin --no-progress

      # Save node cache
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # Create bundles dir
      - run: mkdir ./bundles

      # Run bundle command for android platform
      - run: npm run bundle:android

      - persist_to_workspace:
          root: bundles
          paths:
            - index.android.bundle
      - store_artifacts:
          path: bundles/index.android.bundle

  # Run test on android
  test-android:
    docker:
      - image: circleci/android:api-27-node8-alpha

    working_directory: ~/italia-app

    environment:
      - TERM: "dumb"
      - ANDROID_SDK_BUILD_TOOLS_REVISION: "23.0.1"
      - ANDROID_SDK_BUILD_API_LEVEL="23": "23"

    steps:
      - checkout

      # Restore dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      # Install node dependencies
      - run: npm install --no-package-lock --no-spin --no-progress

      # Save node cache
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # Restore sdk cache
      - restore_cache:
          keys:
            - v1-android-sdkmanager-packages-{{ checksum "scripts/circleci-android-setup.sh" }}
            - v1-android-sdkmanager-packages-


      # Install sdk stuff
      - run:
          command: ./scripts/circleci-android-setup.sh

      # Save sdk cache
      - save_cache:
          paths:
            - /opt/android/sdk/system-images/android-23
            - /opt/android/sdk/system-images/android-19
            - /opt/android/sdk/platforms/android-26
            - /opt/android/sdk/platforms/android-23
            - /opt/android/sdk/platforms/android-19
            - /opt/android/sdk/build-tools/23.0.1
            - /opt/android/sdk/add-ons/addon-google_apis-google-2
          key: v1-android-sdkmanager-packages-{{ checksum "scripts/circleci-android-setup.sh" }}

      # Run gradle tests
      - run:
          command: cd android && ./gradlew test

workflows:
  version: 2

  build:
    jobs:

      # Test Javascript
      - test-js-node-8

      # Test Android
      - build-js-bundle
      - test-android:
          requires:
            - build-js-bundle
